ad_list = {"Hu Dukaan": [("Cafeteria", 2), ("Dhaaba", 2), ("East Street", 3)],
           "East Street": [("Central Street 2", 4), ("Hu Dukaan", 3)],
           "Cafeteria": [("Central Lower Ground", 2), ("Gym", 4), ("Swimming Pool", 4), ("Amphitheater", 2), ("Hu Dukaan", 2), ("Central Street 2", 3)],
           "Central Lower Ground": [("Circuits and Electronic Lab 1", 3), ("Music Room", 2), ("Library", 4), ("Cafeteria", 2)],
           "Circuits and Electronic Lab 1": [("Music Room", 2), ("Central Street 1", 3), ("Central Lower Ground", 3)],
           "Music Room": [("Linux And Networking Lab", 2), ("Central Lower Ground", 2), ("Circuits and Electronic Lab 1", 2)],
           "Linux And Networking Lab": [("Visualization And Graphics Lab", 2), ("Music Room", 2)],
           "Visualization And Graphics Lab": [("Linux And Networking Lab", 2)],
           "Swimming Pool": [("Cafeteria", 4)],
           "Gym": [("Cafeteria", 4)],
           "Dhaaba": [("Zen Garden", 3), ("Multipurpose Sports Courts 1", 3), ("Hu Dukaan", 2)],
           "Zen Garden": [("Multipurpose Sports Courts 1", 2), ("Dhaaba", 3)],
           "Central Street 1": [("Circuits and Electronic Lab 1", 3), ("Wellness Courtyard", 2), ("Office Of Student Life", 2), ("Reception", 3), ("Library", 3), ("Central Street 2", 2)],
           "Wellness Courtyard": [("Central Street 1", 2), ("Office Of Student Life", 1)],
           "Office Of Student Life": [("Central Street 1", 2), ("Wellness Courtyard", 1)],
           "Central Street 2": [("Earth Courtyard", 3), ("Student Lounge", 4), ("Central Street 1", 2), ("Soorty Hall", 3), ("East Street", 4), ("East Zone", 2), ("Cafeteria", 3)],
           "Earth Courtyard": [("Central Street 2", 3), ("Learn Courtyard", 2), ("Arif Habib Classroom", 1), ("Air Courtyard", 1), ("Water Courtyard", 1)],
           "Air Courtyard": [("Earth Courtyard", 1), ("Arif Habib Classroom", 2), ("Water Courtyard", 1)],
           "Water Courtyard": [("Earth Courtyard", 1), ("Fire Courtyard", 1), ("Air Courtyard", 1)],
           "Fire Courtyard": [("Water Courtyard", 1), ("Chemistry Lab", 1), ("Digital Systems and Instrumentation Lab", 1), ("Student Lounge", 4)],
           "Chemistry Lab": [("Fire Courtyard", 1), ("Digital Systems and Instrumentation Lab", 1)],
           "Digital Systems and Instrumentation Lab": [("Fire Courtyard", 1), ("Chemistry Lab", 1)],
           "Arif Habib Classroom": [("Earth Courtyard", 1), ("Air Courtyard", 2)],
           "Learn Courtyard": [("Earth Courtyard", 2)],
           "Student Lounge": [("Amphitheater", 2), ("Central Street 2", 4), ("Multipurpose Sports Courts 1", 3), ("Soorty Hall", 2), ("Fire Courtyard", 4)],
           "Multipurpose Sports Courts 1": [("Student Lounge", 2), ("Zen Garden", 2), ("Dhaaba", 3)],
           "Amphitheater": [("Student Lounge", 2), ("Engineering Workshop", 2), ("Cafeteria", 2)],
           "Engineering Workshop": [("Amphitheater", 2)],
           "Soorty Hall": [("Student Lounge", 2), ("Central Street 2", 3), ],
           "Library": [("Central Lower Ground", 3), ("Central Street 1", 3), ("Reception", 1)],
           "Reception": [("Central Street 1", 3), ("Student Center", 1), ("Library", 1), ("Elevator", 1)],
           "Student Center": [("Reception", 1), ("Elevator", 1)],
           "Elevator": [("Student Center", 1), ("Reception", 1), ("West Zone 1", 3), ("Auditorium Hall", 3), ("Playground", 4), ("Prayer Area", 5)],
           "East Zone": [("West Zone 1", 3), ("Tariq Rafi Lecture Theater", 2), ("Film Studio", 4), ("West Zone 2", 2), ("Central Street 2", 2)],
           "Tariq Rafi Lecture Theater": [("Film Studio", 2), ("East Zone", 4), ("Mehfil", 4)],
           "Film Studio": [("Tariq Rafi Lecture Theater", 2), ("East Zone", 4)],
           "Mehfil": [("Tariq Rafi Lecture Theater", 4)],
           "West Zone 1": [("East Zone", 3), ("Faulty Pod", 4), ("Playground", 2), ("West Zone 2", 2), ("Elevator", 3)],
           "West Zone 2": [("East Zone", 2), ("West Zone 1", 2), ("Baithak", 3), ("Amin Issa Tai Classroom", 3), ("Design Studio", 3)],
           "Amin Issa Tai Classroom": [("Design Studio", 1), ("West Zone 2", 3), ("Baithak", 2)],
           "Design Studio": [("West Zone 2", 3), ("Amin Issa Tai Classroom", 1)],
           "Baithak": [("Amin Issa Tai Classroom", 2), ("West Zone 2", 3)],
           "Auditorium Hall": [("Elevator", 3)],
           "Playground": [("Elevator", 4), ("West Zone 1", 2)],
           "Faulty Pod": [("West Zone 1", 4)],
           "Prayer Area": [("Elevator", 5), ("Faculty Cafeteria", 2), ("Day Care", 1)],
           "Faculty Cafeteria": [("Prayer Area", 2)],
           "Day Care": [("Prayer Area", 1)]}

options = []
for key in ad_list.keys():
    options.append(key)
 

for i in options: 
    print("<option value='{name}'>{name}</option>".format(name=i))
